// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR7zDhLXHp8-sjIE1ibZ37SQgn2PQLwXk',
    appId: '1:887651742802:web:f0521ad6fb0adfcf3ddb8b',
    messagingSenderId: '887651742802',
    projectId: 'jalu-bakery-daily-hisab',
    authDomain: 'jalu-bakery-daily-hisab.firebaseapp.com',
    storageBucket: 'jalu-bakery-daily-hisab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV9Fhi_VSa-t0zXjBFKUXQVma-tNJjiW8',
    appId: '1:887651742802:android:dd4db66a679c15873ddb8b',
    messagingSenderId: '887651742802',
    projectId: 'jalu-bakery-daily-hisab',
    storageBucket: 'jalu-bakery-daily-hisab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvRq5s4ZDp0DKnabIKbq16VDDdrbN3MyM',
    appId: '1:887651742802:ios:cecb4529aab50a1f3ddb8b',
    messagingSenderId: '887651742802',
    projectId: 'jalu-bakery-daily-hisab',
    storageBucket: 'jalu-bakery-daily-hisab.firebasestorage.app',
    iosBundleId: 'com.example.dailyHisab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvRq5s4ZDp0DKnabIKbq16VDDdrbN3MyM',
    appId: '1:887651742802:ios:cecb4529aab50a1f3ddb8b',
    messagingSenderId: '887651742802',
    projectId: 'jalu-bakery-daily-hisab',
    storageBucket: 'jalu-bakery-daily-hisab.firebasestorage.app',
    iosBundleId: 'com.example.dailyHisab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR7zDhLXHp8-sjIE1ibZ37SQgn2PQLwXk',
    appId: '1:887651742802:web:f7cc7fba11e361e13ddb8b',
    messagingSenderId: '887651742802',
    projectId: 'jalu-bakery-daily-hisab',
    authDomain: 'jalu-bakery-daily-hisab.firebaseapp.com',
    storageBucket: 'jalu-bakery-daily-hisab.firebasestorage.app',
  );
}
