import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import '../firebase_options.dart';
import '../services/backup_restore_service.dart';
import 'change_requests_page.dart';

class AdminPage extends StatefulWidget { const AdminPage({super.key}); @override State<AdminPage> createState()=>_AdminPageState(); }
class _AdminPageState extends State<AdminPage> {
  final db=FirebaseFirestore.instance;
  Stream<QuerySnapshot<Map<String,dynamic>>> get usersStream=>db.collection('users').snapshots();
  Future<List<Map<String,dynamic>>> shops() async { final s=await db.collection('sharedData').doc('dailyHisab').collection('retailShops').get(); return s.docs.map((d)=>{'id':d.id,...d.data()}).where((x)=>x['active']!=false).toList(); }
  Future<void> createUser() async { final email=TextEditingController(),pass=TextEditingController(); String role='user'; String? shopId,shopName; final ss=await shops(); if(!mounted)return; await showDialog(context:context,builder:(dc)=>StatefulBuilder(builder:(c,setD)=>AlertDialog(title:const Text('Create User'),content:SingleChildScrollView(child:Column(children:[TextField(controller:email,decoration:const InputDecoration(labelText:'Email')),TextField(controller:pass,obscureText:true,decoration:const InputDecoration(labelText:'Temporary Password')),DropdownButtonFormField<String>(initialValue:role,items:const[DropdownMenuItem(value:'user',child:Text('Business User')),DropdownMenuItem(value:'retail_shop_user',child:Text('Retail Shop User'))],onChanged:(v)=>setD((){role=v??'user';if(role!='retail_shop_user'){shopId=null;shopName=null;}})),if(role=='retail_shop_user')DropdownButtonFormField<String>(initialValue:shopId,items:ss.map((s)=>DropdownMenuItem(value:s['id'].toString(),child:Text(s['name']?.toString()??'Shop'))).toList(),onChanged:(v)=>setD((){shopId=v;shopName=ss.where((s)=>s['id'].toString()==v).firstOrNull?['name']?.toString();}))])),actions:[TextButton(onPressed:()=>Navigator.pop(dc),child:const Text('CANCEL')),FilledButton(onPressed:()async{if(!email.text.contains('@')||pass.text.length<6)return;try{final app=await Firebase.initializeApp(name:'admin-create-${DateTime.now().microsecondsSinceEpoch}',options:DefaultFirebaseOptions.currentPlatform);final auth=FirebaseAuth.instanceFor(app:app);final cr=await auth.createUserWithEmailAndPassword(email:email.text.trim(),password:pass.text);await db.collection('users').doc(cr.user!.uid).set({'email':email.text.trim(),'role':role,'status':'pending','createdAt':FieldValue.serverTimestamp(),if(shopId!=null)'shopId':shopId,if(shopName!=null)'shopName':shopName});await app.delete();if(dc.mounted)Navigator.pop(dc);if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('User created and sent for approval.')));}catch(e){if(dc.mounted)ScaffoldMessenger.of(dc).showSnackBar(SnackBar(content:Text('Unable to create user: $e')));}},child:const Text('CREATE'))])); email.dispose();pass.dispose(); }
  Future<void> setStatus(String uid,String status)=>db.collection('users').doc(uid).update({'status':status});
  Future<void> reject(String uid)=>db.collection('users').doc(uid).update({'status':'rejected','rejectedAt':FieldValue.serverTimestamp(),'rejectedBy':FirebaseAuth.instance.currentUser?.uid,'rejectedByEmail':FirebaseAuth.instance.currentUser?.email});
  Future<void> backup()async{try{await BackupRestoreService.instance.saveBackup();if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Backup completed.')));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Backup failed: $e')));}}
  Future<void> restore()async{try{final n=await BackupRestoreService.instance.restoreFromFile();if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Restore completed: $n records.')));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Restore failed: $e')));}}
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Admin'),actions:[IconButton(onPressed:createUser,icon:const Icon(Icons.person_add_alt_1))]),body:ListView(padding:const EdgeInsets.all(16),children:[const Card(child:ListTile(title:Text('User Management',style:TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('Create, approve, reject and deactivate users.'))),Row(children:[Expanded(child:FilledButton.icon(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const ChangeRequestsPage())),icon:const Icon(Icons.approval),label:const Text('CHANGE APPROVALS'))),const SizedBox(width:8),Expanded(child:OutlinedButton.icon(onPressed:backup,icon:const Icon(Icons.backup),label:const Text('BACKUP')))]),OutlinedButton.icon(onPressed:restore,icon:const Icon(Icons.restore),label:const Text('RESTORE BACKUP')),const SizedBox(height:12),const Text('Users',style:TextStyle(fontSize:19,fontWeight:FontWeight.bold)),StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:usersStream,builder:(c,s){if(s.hasError)return Text('Unable to load users: ${s.error}');if(!s.hasData)return const CircularProgressIndicator();return Column(children:s.data!.docs.map((d){final x=d.data(),role=x['role']?.toString()??'user',status=x['status']?.toString()??'pending',self=d.id==FirebaseAuth.instance.currentUser?.uid;return Card(child:ListTile(title:Text(x['email']?.toString()??d.id),subtitle:Text('Role: $role\nStatus: $status${x['shopName']==null?'':'\nShop: ${x['shopName']}'}'),trailing:self?const Text('YOU'):PopupMenuButton<String>(onSelected:(v){if(v=='approve')setStatus(d.id,'approved');if(v=='reject')reject(d.id);if(v=='disable')setStatus(d.id,'disabled');if(v=='reactivate')setStatus(d.id,'approved');},itemBuilder:(_)=>[if(status=='pending')const PopupMenuItem(value:'approve',child:Text('Approve')),if(status=='pending')const PopupMenuItem(value:'reject',child:Text('Reject')),if(status=='approved')const PopupMenuItem(value:'disable',child:Text('Deactivate')),if(status=='disabled')const PopupMenuItem(value:'reactivate',child:Text('Reactivate'))]));}).toList());})]));
}
