import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import '../firebase_options.dart';
import '../services/backup_restore_service.dart';
import 'change_requests_page.dart';

class AdminPage extends StatefulWidget{const AdminPage({super.key});@override State<AdminPage> createState()=>_AdminPageState();}
class _AdminPageState extends State<AdminPage>{
 final db=FirebaseFirestore.instance;
 Stream<QuerySnapshot<Map<String,dynamic>>> get usersStream=>db.collection('users').snapshots();
 Future<List<Map<String,dynamic>>> getShops()async{final snap=await db.collection('sharedData').doc('dailyHisab').collection('retailShops').get();return snap.docs.map((d)=>{'id':d.id,...d.data()}).where((x)=>x['active']!=false).toList();}
 Future<void> createUser()async{final email=TextEditingController(),password=TextEditingController();String role='user';String? shopId,shopName;final shops=await getShops();if(!mounted)return;await showDialog<void>(context:context,builder:(dialogContext)=>StatefulBuilder(builder:(context,setDialog){return AlertDialog(title:const Text('Create User'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:email,decoration:const InputDecoration(labelText:'Email')),const SizedBox(height:12),TextField(controller:password,obscureText:true,decoration:const InputDecoration(labelText:'Temporary Password')),const SizedBox(height:12),DropdownButtonFormField<String>(initialValue:role,decoration:const InputDecoration(labelText:'Role'),items:const[DropdownMenuItem(value:'user',child:Text('Business User')),DropdownMenuItem(value:'retail_shop_user',child:Text('Retail Shop User'))],onChanged:(v){setDialog((){role=v??'user';if(role!='retail_shop_user'){shopId=null;shopName=null;}});}),if(role=='retail_shop_user')... [const SizedBox(height:12),DropdownButtonFormField<String>(initialValue:shopId,decoration:const InputDecoration(labelText:'Assigned Retail Shop'),items:shops.map((s)=>DropdownMenuItem(value:s['id'].toString(),child:Text(s['name']?.toString()??'Shop'))).toList(),onChanged:(v){final s=shops.where((x)=>x['id'].toString()==v).firstOrNull;setDialog((){shopId=v;shopName=s?['name']?.toString();});})]])),actions:[TextButton(onPressed:()=>Navigator.pop(dialogContext),child:const Text('CANCEL')),FilledButton(onPressed:()async{final e=email.text.trim();if(!e.contains('@')||password.text.length<6){ScaffoldMessenger.of(dialogContext).showSnackBar(const SnackBar(content:Text('Enter a valid email and password of at least 6 characters.')));return;}if(role=='retail_shop_user'&&shopId==null){ScaffoldMessenger.of(dialogContext).showSnackBar(const SnackBar(content:Text('Select the retail shop.')));return;}try{final app=await Firebase.initializeApp(name:'admin-create-${DateTime.now().microsecondsSinceEpoch}',options:DefaultFirebaseOptions.currentPlatform);final auth=FirebaseAuth.instanceFor(app:app);final cred=await auth.createUserWithEmailAndPassword(email:e,password:password.text);final data=<String,dynamic>{'email':e,'role':role,'status':'pending','createdAt':FieldValue.serverTimestamp()};if(shopId!=null)data['shopId']=shopId;if(shopName!=null)data['shopName']=shopName;await db.collection('users').doc(cred.user!.uid).set(data);await app.delete();if(dialogContext.mounted)Navigator.pop(dialogContext);if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('User created and sent for Admin approval.')));}catch(e){if(dialogContext.mounted)ScaffoldMessenger.of(dialogContext).showSnackBar(SnackBar(content:Text('Unable to create user: $e')));}},child:const Text('CREATE'))]));}));email.dispose();password.dispose();}
 Future<void> editUser(String uid,Map<String,dynamic> current)async{String role=current['role']?.toString()??'user';String? shopId=current['shopId']?.toString(),shopName=current['shopName']?.toString();final shops=await getShops();if(!mounted)return;await showDialog<void>(context:context,builder:(dialogContext)=>StatefulBuilder(builder:(context,setDialog){final validShop=shops.any((s)=>s['id'].toString()==shopId);return AlertDialog(title:const Text('Edit User Access'),content:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField<String>(initialValue:role,decoration:const InputDecoration(labelText:'Role'),items:const[DropdownMenuItem(value:'user',child:Text('Business User')),DropdownMenuItem(value:'retail_shop_user',child:Text('Retail Shop User')),DropdownMenuItem(value:'admin',child:Text('Admin'))],onChanged:(v){setDialog((){role=v??'user';if(role!='retail_shop_user'){shopId=null;shopName=null;}});}),if(role=='retail_shop_user')... [const SizedBox(height:12),DropdownButtonFormField<String>(initialValue:validShop?shopId:null,decoration:const InputDecoration(labelText:'Assigned Retail Shop'),items:shops.map((s)=>DropdownMenuItem(value:s['id'].toString(),child:Text(s['name']?.toString()??'Shop'))).toList(),onChanged:(v){final s=shops.where((x)=>x['id'].toString()==v).firstOrNull;setDialog((){shopId=v;shopName=s?['name']?.toString();});})]]),actions:[TextButton(onPressed:()=>Navigator.pop(dialogContext),child:const Text('CANCEL')),FilledButton(onPressed:()async{await db.collection('users').doc(uid).update({'role':role,'shopId':shopId,'shopName':shopName});if(dialogContext.mounted)Navigator.pop(dialogContext);},child:const Text('SAVE'))]));}));}
 Future<void> setStatus(String uid,String status)async=>db.collection('users').doc(uid).update({'status':status});
 Future<void> rejectUser(String uid)async=>db.collection('users').doc(uid).update({'status':'rejected','rejectedAt':FieldValue.serverTimestamp(),'rejectedBy':FirebaseAuth.instance.currentUser?.uid,'rejectedByEmail':FirebaseAuth.instance.currentUser?.email});
 Future<void> takeBackup()async{try{final path=await BackupRestoreService.instance.saveBackup();if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(path==null?'Backup cancelled.':'Backup saved successfully.')));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Backup failed: $e')));}}
 Future<void> restoreBackup()async{try{final count=await BackupRestoreService.instance.restoreFromFile();if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(count==0?'Restore cancelled or no records found.':'Restore completed: $count records restored.')));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Restore failed: $e')));}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Admin'),actions:[IconButton(onPressed:createUser,icon:const Icon(Icons.person_add_alt_1))]),body:ListView(padding:const EdgeInsets.all(16),children:[const Card(child:ListTile(leading:CircleAvatar(child:Icon(Icons.admin_panel_settings)),title:Text('User Management',style:TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('Create users, assign shops, approve and deactivate access.'))),const SizedBox(height:10),Row(children:[Expanded(child:FilledButton.icon(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const ChangeRequestsPage())),icon:const Icon(Icons.approval),label:const Text('CHANGE APPROVALS'))),const SizedBox(width:10),Expanded(child:OutlinedButton.icon(onPressed:takeBackup,icon:const Icon(Icons.backup_outlined),label:const Text('TAKE BACKUP')))]),const SizedBox(height:10),SizedBox(width:double.infinity,child:OutlinedButton.icon(onPressed:restoreBackup,icon:const Icon(Icons.restore_outlined),label:const Text('RESTORE BACKUP'))),const SizedBox(height:18),const Text('Users',style:TextStyle(fontSize:19,fontWeight:FontWeight.bold)),const SizedBox(height:8),StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:usersStream,builder:(context,snapshot){if(snapshot.hasError)return Text('Unable to load users: ${snapshot.error}');if(!snapshot.hasData)return const Center(child:CircularProgressIndicator());final docs=snapshot.data!.docs;if(docs.isEmpty)return const Padding(padding:EdgeInsets.all(24),child:Text('No users found.'));return Column(children:docs.map((doc){final data=doc.data(),role=data['role']?.toString()??'user',status=data['status']?.toString()??'pending',self=doc.id==FirebaseAuth.instance.currentUser?.uid;final pending=status=='pending';return Card(margin:const EdgeInsets.only(bottom:8),child:ListTile(leading:CircleAvatar(child:Icon(role=='admin'?Icons.admin_panel_settings:role=='retail_shop_user'?Icons.store:Icons.person)),title:Text(data['email']?.toString()??doc.id),subtitle:Text('Role: $role\nStatus: $status${data['shopName']==null?'':'\nShop: ${data['shopName']}'}'),isThreeLine:true,trailing:self?const Text('YOU'):PopupMenuButton<String>(onSelected:(value){if(value=='edit')editUser(doc.id,data);if(value=='approve')setStatus(doc.id,'approved');if(value=='reject')rejectUser(doc.id);if(value=='disable')setStatus(doc.id,'disabled');if(value=='reactivate')setStatus(doc.id,'approved');},itemBuilder:(context)=>[const PopupMenuItem(value:'edit',child:Text('Edit Access')),if(pending)const PopupMenuItem(value:'approve',child:Text('Approve')),if(pending)const PopupMenuItem(value:'reject',child:Text('Reject')),if(status=='approved')const PopupMenuItem(value:'disable',child:Text('Deactivate')),if(status=='disabled')const PopupMenuItem(value:'reactivate',child:Text('Reactivate'))])));} ).toList());})]));
}
