import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import '../services/dashboard_service.dart';

class DashboardPage extends StatefulWidget { const DashboardPage({super.key}); @override State<DashboardPage> createState()=>_DashboardPageState(); }
class _DashboardPageState extends State<DashboardPage>{
  DateTime fromDate=DateTime.now(),toDate=DateTime.now(); String filterType='Date'; DashboardSummary? summary; bool loading=true; String? errorMessage; bool hideProfit=true;
  @override void initState(){super.initState();_loadRole();_loadDashboard();}
  Future<void> _loadRole()async{final uid=FirebaseAuth.instance.currentUser?.uid;if(uid==null)return;final p=(await FirebaseFirestore.instance.collection('users').doc(uid).get()).data()??{};if(mounted)setState(()=>hideProfit=p['role']!='admin');}
  String _money(double v)=>'₹${v.toStringAsFixed(2)}'; String _dateText(DateTime d)=>'${d.day.toString().padLeft(2,'0')}-${d.month.toString().padLeft(2,'0')}-${d.year}';
  Future<void> _loadDashboard()async{if(mounted)setState((){loading=true;errorMessage=null;});try{final r=await DashboardService.instance.calculate(from:fromDate,to:DateTime(toDate.year,toDate.month,toDate.day,23,59,59));if(mounted)setState(()=>summary=r);}catch(e){if(mounted)setState(()=>errorMessage=e.toString());}finally{if(mounted)setState(()=>loading=false);}}
  Future<void> _pickDate()async{final p=await showDatePicker(context:context,initialDate:fromDate,firstDate:DateTime(2020),lastDate:DateTime(2100));if(p==null)return;setState((){fromDate=p;toDate=p;});await _loadDashboard();}
  Future<void> _pickRange()async{final r=await showDateRangePicker(context:context,firstDate:DateTime(2020),lastDate:DateTime(2100),initialDateRange:DateTimeRange(start:fromDate,end:toDate));if(r==null)return;setState((){fromDate=r.start;toDate=r.end;});await _loadDashboard();}
  Future<void> _pickMonth()async{final p=await showDatePicker(context:context,initialDate:fromDate,firstDate:DateTime(2020),lastDate:DateTime(2100),initialDatePickerMode:DatePickerMode.year);if(p==null)return;setState((){fromDate=DateTime(p.year,p.month,1);toDate=DateTime(p.year,p.month+1,0);});await _loadDashboard();}
  Future<void> _changeFilter(String v)async{setState(()=>filterType=v);if(v=='Date')await _pickDate();else if(v=='Date Range')await _pickRange();else await _pickMonth();}
  String _periodText(){if(filterType=='Date')return _dateText(fromDate);if(filterType=='Month')return '${fromDate.month}/${fromDate.year}';return '${_dateText(fromDate)} to ${_dateText(toDate)}';}
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Dashboard'),actions:[IconButton(onPressed:loading?null:_loadDashboard,icon:const Icon(Icons.refresh))]),body:RefreshIndicator(onRefresh:_loadDashboard,child:ListView(physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.all(8),children:[Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Dashboard Period',style:TextStyle(fontWeight:FontWeight.bold)),const SizedBox(height:10),DropdownButtonFormField<String>(initialValue:filterType,items:const[DropdownMenuItem(value:'Date',child:Text('Date-wise')),DropdownMenuItem(value:'Date Range',child:Text('Date Range-wise')),DropdownMenuItem(value:'Month',child:Text('Month-wise'))],onChanged:(v){if(v!=null)_changeFilter(v);},decoration:const InputDecoration(labelText:'Filter',border:OutlineInputBorder())),const SizedBox(height:10),InkWell(onTap:(){if(filterType=='Date')_pickDate();else if(filterType=='Date Range')_pickRange();else _pickMonth();},child:InputDecorator(decoration:const InputDecoration(labelText:'Selected Period',border:OutlineInputBorder()),child:Text(_periodText())))]))),const SizedBox(height:10),if(loading)const Padding(padding:EdgeInsets.all(40),child:Center(child:CircularProgressIndicator()))else if(errorMessage!=null)Card(child:Padding(padding:const EdgeInsets.all(20),child:Column(children:[const Icon(Icons.error_outline,size:42),const SizedBox(height:8),const Text('Unable to load dashboard'),Text(errorMessage!,textAlign:TextAlign.center),FilledButton(onPressed:_loadDashboard,child:const Text('RETRY'))])))else if(summary!=null)_content(summary!)else const Card(child:Padding(padding:EdgeInsets.all(25),child:Text('No dashboard data.')))]));
  Widget _content(DashboardSummary d){final productionMetrics=<_Metric>[_Metric('Production','${d.productionBoxes.toStringAsFixed(0)} Boxes',Icons.factory_outlined),_Metric('Expenses',_money(d.expenses),Icons.receipt_long_outlined),_Metric('Salary',_money(d.salary),Icons.people_outline)];if(!hideProfit)productionMetrics.add(_Metric('Profit / Loss',_money(d.profitLoss),d.profitLoss>=0?Icons.trending_up:Icons.trending_down));return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Business Overview',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const SizedBox(height:8),_grid([_Metric('Sales',_money(d.sales),Icons.point_of_sale_outlined),_Metric('Payments Received',_money(d.paymentsReceived),Icons.arrow_downward),_Metric('Payment Made',_money(d.paymentsMade),Icons.arrow_upward),_Metric('Cash Payment',_money(d.cashPaymentsMade),Icons.money_outlined),_Metric('Bank Payment',_money(d.bankPaymentsMade),Icons.account_balance_outlined),_Metric('Outstanding',_money(d.outstanding),Icons.account_balance_wallet_outlined),_Metric('Commission',_money(d.commission),Icons.percent_outlined)]),const SizedBox(height:14),const Text('Production & Expenses',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const SizedBox(height:8),_grid(productionMetrics),const SizedBox(height:14),const Text('Capital',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const SizedBox(height:8),_grid([_Metric('Capital Received',_money(d.capitalReceived),Icons.arrow_downward),_Metric('Capital Returned',_money(d.capitalReturned),Icons.arrow_upward),_Metric('Capital Balance',_money(d.capitalReceived-d.capitalReturned),Icons.account_balance_outlined)])]);}
  Widget _grid(List<_Metric> items)=>LayoutBuilder(builder:(context,c){final columns=c.maxWidth>=700?4:2;return GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:items.length,gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:columns,crossAxisSpacing:7,mainAxisSpacing:7,childAspectRatio:columns==4?1.65:1.55),itemBuilder:(_,i){final m=items[i];final cs=Theme.of(context).colorScheme;return Card(color:cs.surfaceContainerHighest,margin:EdgeInsets.zero,child:Padding(padding:const EdgeInsets.all(7),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(m.icon,size:20,color:cs.primary),const SizedBox(height:3),Text(m.title,textAlign:TextAlign.center,style:TextStyle(fontSize:11,fontWeight:FontWeight.w600,color:cs.onSurfaceVariant)),const SizedBox(height:2),FittedBox(child:Text(m.value,style:const TextStyle(fontSize:14,fontWeight:FontWeight.bold)))])));});});
}
class _Metric{final String title,value;final IconData icon;const _Metric(this.title,this.value,this.icon);}
