import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';

class ProductionStockPage extends StatelessWidget {
  const ProductionStockPage({super.key});
  CollectionReference<Map<String,dynamic>> c(String n)=>FirebaseFirestore.instance.collection('sharedData').doc('dailyHisab').collection(n);
  double n(dynamic v)=>v is num?v.toDouble():double.tryParse('$v')??0;
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Production Unit Stock')),body:StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:c('products').snapshots(),builder:(context,ps){if(ps.hasError)return Center(child:Text('Unable to load products: ${ps.error}'));if(!ps.hasData)return const Center(child:CircularProgressIndicator());final products=ps.data!.docs.where((d)=>d.data()['active']!=false).toList();return StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:c('production').snapshots(),builder:(context,pro){return StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:c('stockTransfers').snapshots(),builder:(context,tr){if(pro.hasError||tr.hasError)return Center(child:Text('Unable to load production stock. ${pro.error??tr.error}'));if(!pro.hasData||!tr.hasData)return const Center(child:CircularProgressIndicator());final made=pro.data!.docs.map((d)=>d.data()).toList();final moved=tr.data!.docs.map((d)=>d.data()).toList();return ListView(padding:const EdgeInsets.all(16),children:[const Card(child:ListTile(leading:CircleAvatar(child:Icon(Icons.factory_outlined)),title:Text('Production Unit',style:TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('Produced quantity less quantities transferred to retail shops.'))),const SizedBox(height:12),...products.map((p){final id=p.id;final production=made.where((x)=>x['productId']?.toString()==id).fold<double>(0,(s,x)=>s+n(x['quantity']));final transferred=moved.where((x)=>x['productId']?.toString()==id).fold<double>(0,(s,x)=>s+n(x['quantity']));final stock=production-transferred;return Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.inventory_2_outlined)),title:Text(p.data()['name']?.toString()??id),subtitle:Text('Produced: ${production.toStringAsFixed(2)}  •  Transferred: ${transferred.toStringAsFixed(2)}'),trailing:Text('${stock.toStringAsFixed(2)} Box',style:const TextStyle(fontWeight:FontWeight.bold,fontSize:16))));})]);});});}));}
}
