import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../services/firestore_service.dart';

class ReportsV2Page extends StatefulWidget{const ReportsV2Page({super.key});@override State<ReportsV2Page> createState()=>_ReportsV2PageState();}
class _ReportsV2PageState extends State<ReportsV2Page>{
 final db=FirebaseFirestore.instance;String report='Sales',period='Daily',stockLocation='Production Unit';DateTime from=DateTime.now(),to=DateTime.now();bool loading=true,retailUser=false;String? shopId,shopName,error;List<Map<String,dynamic>> rows=[];List<Map<String,dynamic>> shops=[],products=[];
 final adminTypes=const['Sales','Receipt','Payments','Outstanding','Commission','Production','Expenses','Salary','Capital','Stock Management','Cash Management','Profit/Loss'];
 final retailTypes=const['Sales','Receipt','Payments','Outstanding','Commission','Stock Management','Stock Tally','Cash Management'];
 CollectionReference<Map<String,dynamic>> c(String n)=>db.collection('sharedData').doc('dailyHisab').collection(n);
 double n(dynamic v)=>v is num?v.toDouble():double.tryParse('$v')??0;DateTime d(dynamic v)=>v is Timestamp?v.toDate():v is DateTime?v:DateTime.fromMillisecondsSinceEpoch(0);String money(dynamic v)=>'₹${n(v).toStringAsFixed(2)}';String fd(DateTime x)=>'${x.day.toString().padLeft(2,'0')}-${x.month.toString().padLeft(2,'0')}-${x.year}';bool range(DateTime x)=>!x.isBefore(DateTime(from.year,from.month,from.day))&&!x.isAfter(DateTime(to.year,to.month,to.day,23,59,59));
 @override void initState(){super.initState();_init();}
 Future<void> _init()async{try{final p=await FirestoreService.instance.currentProfile();retailUser=p['role']=='retail_shop_user';shopId=retailUser?p['shopId']?.toString():null;shopName=retailUser?p['shopName']?.toString():null;if(retailUser&&shopId==null)throw StateError('No retail shop is assigned to this user.');final ps=await c('products').get();products=ps.docs.map((x)=>{'id':x.id,...x.data()}).where((x)=>x['active']!=false).toList();if(retailUser){final s=await c('retailShops').doc(shopId).get();if(s.exists)shopName=s.data()?['name']?.toString()??shopName;shops=s.exists?[{'id':s.id,...s.data()!}]:[];}else{final s=await c('retailShops').get();shops=s.docs.map((x)=>{'id':x.id,...x.data()}).where((x)=>x['active']!=false).toList();}}catch(e){error='$e';}if(mounted){setState(()=>loading=false);_load();}}
 Future<List<Map<String,dynamic>>> coll(String name)async{Query<Map<String,dynamic>> q=c(name);if(retailUser&&shopId!=null&&{'sales','transactions','stockTransfers','stockOtherReceived'}.contains(name))q=q.where('shopId',isEqualTo:shopId);final s=await q.get();return s.docs.map((x)=>{'id':x.id,...x.data()}).where((x)=>range(d(x['date']))).toList();}
 Future<List<Map<String,dynamic>>> collAll(String name)async{Query<Map<String,dynamic>> q=c(name);if(retailUser&&shopId!=null&&{'sales','transactions','stockTransfers','stockOtherReceived'}.contains(name))q=q.where('shopId',isEqualTo:shopId);final s=await q.get();return s.docs.map((x)=>{'id':x.id,...x.data()}).toList();}
 void periodSet(String v){final now=DateTime.now();DateTime a=now,b=now;if(v=='Monthly'){a=DateTime(now.year,now.month,1);b=DateTime(now.year,now.month+1,0);}else if(v=='Quarterly'){final m=((now.month-1)~/3)*3+1;a=DateTime(now.year,m,1);b=DateTime(now.year,m+3,0);}else if(v=='6 Monthly'){final m=now.month<=6?1:7;a=DateTime(now.year,m,1);b=DateTime(now.year,m+6,0);}else if(v=='Yearly'){a=DateTime(now.year,1,1);b=DateTime(now.year,12,31);}setState((){period=v;from=a;to=b;});_load();}
 Future<void> _load()async{if(!mounted)return;setState(()=>loading=true);try{List<Map<String,dynamic>> out=[];if(report=='Sales'||report=='Outstanding'||report=='Commission'){out=await coll('sales');if(!retailUser&&shopId!=null)out=out.where((x)=>x['shopId']?.toString()==shopId).toList();if(report=='Outstanding')out=out.where((x)=>n(x['outstanding'])>0).toList();}else if(report=='Receipt'||report=='Payments'){out=await coll('transactions');final t=report=='Receipt'?'Receipt':'Payment';out=out.where((x)=>x['type']?.toString()==t).toList();}else if(report=='Production')out=await coll('production');else if(report=='Expenses')out=await coll('productionExpenses');else if(report=='Salary')out=await coll('salary');else if(report=='Capital')out=await coll('capital');else if(report=='Stock Management')out=await stock();else if(report=='Stock Tally')out=await stockTally();else if(report=='Cash Management')out=await cash();else if(report=='Profit/Loss')out=await profit();out.sort((a,b)=>d(b['date']).compareTo(d(a['date'])));if(mounted)setState(()=>rows=out);}catch(e){if(mounted)setState(()=>error='$e');}if(mounted)setState(()=>loading=false);}
 Future<List<Map<String,dynamic>>> stock()async{final loc=retailUser?'Retail Shop':stockLocation;final p=await coll('production'),t=await coll('stockTransfers'),r=await coll('stockOtherReceived'),s=await coll('sales');final out=<Map<String,dynamic>>[];final sid=shopId;for(final x in products){final id=x['id'].toString();double made=0,incoming=0,other=0,sold=0;for(final z in p){if(z['productId']?.toString()==id)made+=n(z['quantity']).abs();}for(final z in t){if(z['productId']?.toString()==id&&((loc=='Production Unit')||z['shopId']?.toString()==sid))incoming+=n(z['quantity']).abs();}for(final z in r){if(z['productId']?.toString()==id&&z['shopId']?.toString()==sid)other+=n(z['quantity']).abs();}for(final z in s){if(loc=='Retail Shop'&&sid!=null&&z['shopId']?.toString()!=sid)continue;final items=z['items'];if(items is List)for(final i in items){if(i is Map&&i['productId']?.toString()==id)sold+=n(i['quantity']).abs();}}final bal=loc=='Production Unit'?made-incoming:incoming+other-sold;out.add({'date':Timestamp.fromDate(to),'productName':x['name']??'Product','quantity':bal,'production':made,'transferred':incoming,'received':other,'sold':sold});}return out;}
 bool before(dynamic v)=>d(v).isBefore(DateTime(from.year,from.month,from.day));
 bool inPeriod(dynamic v)=>range(d(v));
 double itemQty(Map<String,dynamic> sale,String id){final items=sale['items'];if(items is! List)return 0;double q=0;for(final i in items){if(i is Map&&i['productId']?.toString()==id)q+=n(i['quantity']).abs();}return q;}
 Future<List<Map<String,dynamic>>> stockTally()async{if(!retailUser||shopId==null)return stock();final t=await collAll('stockTransfers'),r=await collAll('stockOtherReceived'),s=await collAll('sales');final out=<Map<String,dynamic>>[];for(final x in products){final id=x['id'].toString();double opening=0,received=0,other=0,soldBefore=0,sold=0;for(final z in t){if(z['productId']?.toString()!=id)continue;final q=n(z['quantity']).abs();if(before(z['date']))opening+=q;else if(inPeriod(z['date']))received+=q;}for(final z in r){if(z['productId']?.toString()!=id)continue;final q=n(z['quantity']).abs();if(before(z['date']))opening+=q;else if(inPeriod(z['date']))other+=q;}for(final z in s){final q=itemQty(z,id);if(before(z['date']))soldBefore+=q;else if(inPeriod(z['date']))sold+=q;}opening-=soldBefore;final balance=opening+received+other-sold;out.add({'date':Timestamp.fromDate(to),'productName':x['name']??'Product','opening':opening,'received':received+other,'sold':sold,'balance':balance});}return out;}
 Future<List<Map<String,dynamic>>> cash()async{final tx=await coll('transactions'),s=await coll('sales');final out=<Map<String,dynamic>>[];for(final x in tx){final a=x['account']?.toString()??'Cash';final typ=x['type']?.toString()??'';final sign=(typ=='Receipt')?1:-1;out.add({'date':x['date'],'particular':'$typ - ${x['partyName']??x['description']??''}','amount':n(x['amount'])*sign,'account':a,'in':sign>0?n(x['amount']):0,'out':sign<0?n(x['amount']):0});}for(final x in s){final a=x['paymentAccount']?.toString()??'Cash';final v=n(x['paymentReceived']);if(v>0)out.add({'date':x['date'],'particular':'Sales Collection - ${x['shopName']??shopName??''}','amount':v,'account':a,'in':v,'out':0});}return out;}
 Future<List<Map<String,dynamic>>> profit()async{final s=await coll('sales'),e=await coll('productionExpenses'),sal=await coll('salary');final gross=s.fold(0.0,(a,x)=>a+n(x['grossAmount'])),com=s.fold(0.0,(a,x)=>a+n(x['commission'])),ex=e.fold(0.0,(a,x)=>a+n(x['amount'])),sa=sal.fold(0.0,(a,x)=>a+n(x['amount']));return[{'particular':'Gross Sales','amount':gross},{'particular':'Commission','amount':com},{'particular':'Expenses','amount':ex},{'particular':'Salary','amount':sa},{'particular':'Profit / Loss','amount':gross-com-ex-sa}];}
 String part(Map<String,dynamic>x)=>(x['particular']??x['shopName']??x['productName']??x['partyName']??x['workerName']??x['type']??x['head']??'').toString();double amt(Map<String,dynamic>x)=>n(x['amount']??x['quantity']);
 Widget cashSummary(){final ci=rows.where((x)=>(x['account']??'Cash')=='Cash').fold(0.0,(a,x)=>a+n(x['in'])),co=rows.where((x)=>(x['account']??'Cash')=='Cash').fold(0.0,(a,x)=>a+n(x['out'])),bi=rows.where((x)=>(x['account']??'Cash')=='Bank').fold(0.0,(a,x)=>a+n(x['in'])),bo=rows.where((x)=>(x['account']??'Cash')=='Bank').fold(0.0,(a,x)=>a+n(x['out']));return Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(children:[Text('${shopName??''} - End of Day Cash / Bank Tally',style:const TextStyle(fontSize:17,fontWeight:FontWeight.bold)),const SizedBox(height:10),Row(mainAxisAlignment:MainAxisAlignment.spaceAround,children:[_box('Cash In',ci),_box('Cash Out',co),_box('Cash Net',ci-co)]),const Divider(),Row(mainAxisAlignment:MainAxisAlignment.spaceAround,children:[_box('Bank In',bi),_box('Bank Out',bo),_box('Bank Net',bi-bo)])])));}
 Widget _box(String t,double v)=>Column(children:[Text(t,style:const TextStyle(fontWeight:FontWeight.w600)),Text(money(v),style:const TextStyle(fontSize:16,fontWeight:FontWeight.bold))]);
 Future<void> pdf()async{if(rows.isEmpty)return;await Printing.layoutPdf(onLayout:(f)async{final doc=pw.Document();doc.addPage(pw.MultiPage(pageFormat:PdfPageFormat.a4,build:(_)=>[pw.Text('DAILY HISAB - $report REPORT',style:pw.TextStyle(fontSize:18,fontWeight:pw.FontWeight.bold)),pw.Text('Period: ${fd(from)} to ${fd(to)}'),if(retailUser)pw.Text('Retail Shop: ${shopName??''}'),if(report=='Stock Management')pw.Text('Stock Location: ${retailUser?'Retail Shop':stockLocation}'),pw.SizedBox(height:10),if(report=='Stock Tally')pw.TableHelper.fromTextArray(headers:const['Product','Opening','Received','Sold','Balance'],data:rows.map((x)=>[x['productName'],n(x['opening']).toStringAsFixed(2),n(x['received']).toStringAsFixed(2),n(x['sold']).toStringAsFixed(2),n(x['balance']).toStringAsFixed(2)]).toList()) else pw.TableHelper.fromTextArray(headers:const['Date','Particular','Amount'],data:rows.map((x)=>[fd(d(x['date'])),part(x),amt(x).toStringAsFixed(2)]).toList())]));return doc.save();});}
 List<Widget> filters(){final list=<Widget>[];final types=retailUser?retailTypes:adminTypes;list.add(DropdownButtonFormField<String>(initialValue:types.contains(report)?report:types.first,items:types.map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v){if(v!=null){setState(()=>report=v);_load();}},decoration:const InputDecoration(labelText:'Report',border:OutlineInputBorder())));list.add(const SizedBox(height:10));list.add(DropdownButtonFormField<String>(initialValue:period,items:const['Daily','Monthly','Quarterly','6 Monthly','Yearly'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v){if(v!=null)periodSet(v);},decoration:const InputDecoration(labelText:'Period',border:OutlineInputBorder())));if(!retailUser&&(report=='Sales'||report=='Receipt'||report=='Payments'||report=='Outstanding'||report=='Commission')){list.add(const SizedBox(height:10));list.add(DropdownButtonFormField<String?>(initialValue:shopId,items:[const DropdownMenuItem<String?>(value:null,child:Text('All Retail Shops')),...shops.map((x)=>DropdownMenuItem<String?>(value:x['id'].toString(),child:Text(x['name']?.toString()??'')))],onChanged:(v){setState(()=>shopId=v);_load();},decoration:const InputDecoration(labelText:'Retail Shop',border:OutlineInputBorder())));}if(report=='Stock Management'&&!retailUser){list.add(const SizedBox(height:10));list.add(DropdownButtonFormField<String>(initialValue:stockLocation,items:const['Production Unit','Retail Shop'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v){if(v!=null){setState(()=>stockLocation=v);if(v=='Production Unit')shopId=null;_load();}},decoration:const InputDecoration(labelText:'Stock Location',border:OutlineInputBorder())));if(stockLocation=='Retail Shop'){list.add(const SizedBox(height:10));list.add(DropdownButtonFormField<String?>(initialValue:shopId,items:[const DropdownMenuItem<String?>(value:null,child:Text('Select Retail Shop')),...shops.map((x)=>DropdownMenuItem<String?>(value:x['id'].toString(),child:Text(x['name']?.toString()??'')))],onChanged:(v){setState(()=>shopId=v);_load();},decoration:const InputDecoration(labelText:'Retail Shop',border:OutlineInputBorder())));}}return list;}
 Widget row(Map<String,dynamic>x){if(report=='Stock Tally')return Card(child:ListTile(title:Text(x['productName']?.toString()??'Product',style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('Opening: ${n(x['opening']).toStringAsFixed(2)}  •  Received: +${n(x['received']).toStringAsFixed(2)}  •  Sold: -${n(x['sold']).toStringAsFixed(2)}'),trailing:Text('${n(x['balance']).toStringAsFixed(2)} Box',style:const TextStyle(fontWeight:FontWeight.bold,fontSize:16)));return Card(child:ListTile(title:Text(part(x)),subtitle:Text(fd(d(x['date']))),trailing:Text(report=='Stock Management'?'${amt(x).toStringAsFixed(2)} Box':money(amt(x)),style:const TextStyle(fontWeight:FontWeight.bold))));}
 @override Widget build(BuildContext context){if(loading)return const Scaffold(body:Center(child:CircularProgressIndicator()));return Scaffold(appBar:AppBar(title:const Text('Reports'),actions:[IconButton(onPressed:pdf,icon:const Icon(Icons.picture_as_pdf))]),body:ListView(padding:const EdgeInsets.all(16),children:[if(error!=null)Text(error!),if(retailUser)Card(child:ListTile(leading:const Icon(Icons.store),title:Text(shopName??'Retail Shop'),subtitle:const Text('Reports are locked to your assigned retail shop.'))),...filters(),const SizedBox(height:14),if(report=='Cash Management'&&rows.isNotEmpty)cashSummary(),if(rows.isEmpty)const Padding(padding:EdgeInsets.all(30),child:Text('No data found for selected period.',textAlign:TextAlign.center)),...rows.map(row),if(rows.isNotEmpty&&report!='Cash Management'&&report!='Stock Tally')Padding(padding:const EdgeInsets.all(16),child:Text('TOTAL: ${money(rows.fold(0.0,(a,x)=>a+amt(x)))}',textAlign:TextAlign.right,style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold))) ]));}
}