import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
class ReportsV2Page extends StatefulWidget{const ReportsV2Page({super.key});@override State<ReportsV2Page> createState()=>_ReportsV2PageState();}
class _ReportsV2PageState extends State<ReportsV2Page>{final db=FirebaseFirestore.instance;String report='Sales',period='Daily';String? shopId,productId,assigned;bool retail=false,loading=true;DateTime from=DateTime.now(),to=DateTime.now();List<Map<String,dynamic>> rows=[];List<Map<String,dynamic>> shops=[],products=[];final types=['Sales','Receipt','Payments','Outstanding','Commission','Production','Expenses','Salary','Capital','Stock Management','Cash Management','Profit/Loss'];CollectionReference<Map<String,dynamic>> c(String n)=>db.collection('sharedData').doc('dailyHisab').collection(n);double n(dynamic v)=>v is num?v.toDouble():double.tryParse('$v')??0;DateTime dt(dynamic v)=>v is Timestamp?v.toDate():DateTime.tryParse('$v')??DateTime.fromMillisecondsSinceEpoch(0);String fd(DateTime d)=>'${d.day.toString().padLeft(2,'0')}-${d.month.toString().padLeft(2,'0')}-${d.year}';
 @override void initState(){super.initState();init();}Future<void> init()async{final u=FirebaseAuth.instance.currentUser;if(u!=null){final d=(await db.collection('users').doc(u.uid).get()).data()??{};retail=d['role']=='retail_shop_user';assigned=d['shopId']?.toString();shopId=assigned;}final a=await c('retailShops').get(),b=await c('products').get();if(!mounted)return;setState((){shops=a.docs.map((x)=>{'id':x.id,...x.data()}).where((x)=>x['active']!=false).toList();products=b.docs.map((x)=>{'id':x.id,...x.data()}).where((x)=>x['active']!=false).toList();loading=false;});load();}
 void setPeriod(String v){final now=DateTime.now();DateTime a=now,b=now;if(v=='Monthly'){a=DateTime(now.year,now.month,1);b=DateTime(now.year,now.month+1,0);}else if(v=='Quarterly'){final m=((now.month-1)~/3)*3+1;a=DateTime(now.year,m,1);b=DateTime(now.year,m+3,0);}else if(v=='6 Monthly'){a=DateTime(now.year,now.month<=6?1:7,1);b=DateTime(now.year,now.month<=6?7:13,0);}else if(v=='Yearly'){a=DateTime(now.year,1,1);b=DateTime(now.year,12,31);}setState((){period=v;from=a;to=b;});load();}
 bool inRange(DateTime d)=>!d.isBefore(DateTime(from.year,from.month,from.day))&&!d.isAfter(DateTime(to.year,to.month,to.day,23,59,59));
 Future<List<Map<String,dynamic>>> getc(String name)async{final s=await c(name).get();return s.docs.map((x)=>{'id':x.id,...x.data()}).where((x)=>inRange(dt(x['date']))).toList();}
 Future<void> load()async{if(!mounted)return;setState(()=>loading=true);try{List<Map<String,dynamic>> out=[];if(report=='Sales'||report=='Outstanding'||report=='Commission'){out=await getc('sales');if(shopId!=null)out=out.where((x)=>x['shopId']?.toString()==shopId).toList();if(productId!=null)out=out.where((x)=>x['items'] is List&&(x['items'] as List).any((i)=>i is Map&&i['productId']?.toString()==productId)).toList();if(report=='Outstanding')out=out.where((x)=>n(x['outstanding'])>0).toList();}else if(report=='Receipt'||report=='Payments'){out=await getc('transactions');out=out.where((x)=>x['type']?.toString()==(report=='Receipt'?'Receipt':'Payment')).toList();if(retail)out=out.where((x)=>x['shopId']?.toString()==assigned).toList();}else if(report=='Production')out=await getc('production');else if(report=='Expenses')out=await getc('productionExpenses');else if(report=='Salary')out=await getc('salary');else if(report=='Capital')out=await getc('capital');else if(report=='Cash Management')out=await getc('transactions');else if(report=='Stock Management')out=await getc('stockTransfers');else out=await getc('sales');if(mounted)setState((){rows=out;loading=false;});}catch(e){if(mounted)setState(()=>loading=false);}}
 String label(Map<String,dynamic> x)=>(x['shopName']??x['productName']??x['partyName']??x['workerName']??x['particular']??x['type']??'').toString();double amount(Map<String,dynamic> x)=>n(x['amount']??x['netAmount']??x['grossAmount']??x['paymentReceived']??x['quantity']);
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Reports')),body:loading&&shops.isEmpty?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.all(16),children:[DropdownButtonFormField<String>(initialValue:report,items:types.map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v){if(v!=null){setState(()=>report=v);load();}},decoration:const InputDecoration(labelText:'Report',border:OutlineInputBorder())),const SizedBox(height:10),DropdownButtonFormField<String>(initialValue:period,items:const['Daily','Monthly','Quarterly','6 Monthly','Yearly'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v){if(v!=null)setPeriod(v);},decoration:const InputDecoration(labelText:'Period',border:OutlineInputBorder())),if(!retail&&(report=='Sales'||report=='Receipt'||report=='Payments'||report=='Outstanding'||report=='Commission'))... [const SizedBox(height:10),DropdownButtonFormField<String?>(initialValue:shopId,items:[const DropdownMenuItem<String?>(value:null,child:Text('All Retail Shops')),...shops.map((x)=>DropdownMenuItem<String?>(value:x['id'].toString(),child:Text(x['name']?.toString()??'')))],onChanged:(v){setState(()=>shopId=v);load();},decoration:const InputDecoration(labelText:'Retail Shop',border:OutlineInputBorder()))],if(report=='Sales'||report=='Outstanding'||report=='Production')... [const SizedBox(height:10),DropdownButtonFormField<String?>(initialValue:productId,items:[const DropdownMenuItem<String?>(value:null,child:Text('All Products')),...products.map((x)=>DropdownMenuItem<String?>(value:x['id'].toString(),child:Text(x['name']?.toString()??'')))],onChanged:(v){setState(()=>productId=v);load();},decoration:const InputDecoration(labelText:'Product',border:OutlineInputBorder()))],const SizedBox(height:16),if(loading)const LinearProgressIndicator(),if(!loading&&rows.isEmpty)const Padding(padding:EdgeInsets.all(24),child:Text('No data found for selected period.',textAlign:TextAlign.center)),...rows.map((x)=>Card(child:ListTile(title:Text(label(x)),subtitle:Text(fd(dt(x['date']))),trailing:Text(amount(x).toStringAsFixed(2),style:const TextStyle(fontWeight:FontWeight.bold)))))]));
}
