import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
class RetailStockPage extends StatefulWidget{const RetailStockPage({super.key});@override State<RetailStockPage> createState()=>_RetailStockPageState();}
class _RetailStockPageState extends State<RetailStockPage>{final db=FirebaseFirestore.instance;String? assigned,selected;String name='Retail Shop';bool loading=true;CollectionReference<Map<String,dynamic>> c(String n)=>db.collection('sharedData').doc('dailyHisab').collection(n);double n(dynamic v)=>v is num?v.toDouble():double.tryParse('$v')??0;
 @override void initState(){super.initState();load();}Future<void> load()async{final u=FirebaseAuth.instance.currentUser;if(u!=null){final d=(await db.collection('users').doc(u.uid).get()).data()??{};if(mounted)setState((){assigned=d['role']=='retail_shop_user'?d['shopId']?.toString():null;selected=assigned;name=d['shopName']?.toString()??'Retail Shop';loading=false;});}else if(mounted)setState(()=>loading=false);}
 @override Widget build(BuildContext context){if(loading)return const Scaffold(body:Center(child:CircularProgressIndicator()));return Scaffold(appBar:AppBar(title:Text('$name Stock')),body:StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:c('retailShops').snapshots(),builder:(context,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());final shops=s.data!.docs.where((x)=>x.data()['active']!=false).toList();if(selected==null&&shops.isNotEmpty)selected=shops.first.id;return Column(children:[if(assigned==null&&shops.isNotEmpty)Padding(padding:const EdgeInsets.all(16),child:DropdownButtonFormField<String>(initialValue:selected,items:shops.map((x)=>DropdownMenuItem(value:x.id,child:Text(x.data()['name']?.toString()??x.id))).toList(),onChanged:(v){final x=shops.where((z)=>z.id==v).firstOrNull;setState((){selected=v;name=x?.data()['name']?.toString()??'Retail Shop';});},decoration:const InputDecoration(labelText:'Retail Shop',border:OutlineInputBorder()))),if(selected!=null)Expanded(child:stock(selected!))]);});}
 Widget stock(String shopId)=>StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:c('products').snapshots(),builder:(context,p){if(!p.hasData)return const Center(child:CircularProgressIndicator());return StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:c('stockTransfers').where('shopId',isEqualTo:shopId).snapshots(),builder:(context,t){return StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:c('stockOtherReceived').where('shopId',isEqualTo:shopId).snapshots(),builder:(context,r){return StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:c('sales').where('shopId',isEqualTo:shopId).snapshots(),builder:(context,s){if(t.hasError||r.hasError||s.hasError)return Center(child:Text('Unable to load stock. ${t.error??r.error??s.error}'));if(!t.hasData||!r.hasData||!s.hasData)return const Center(child:CircularProgressIndicator());final tr=t.data!.docs.map((x)=>x.data()).toList(),or=r.data!.docs.map((x)=>x.data()).toList(),sales=s.data!.docs.map((x)=>x.data()).toList();return ListView(padding:const EdgeInsets.all(16),children:[...p.data!.docs.where((x)=>x.data()['active']!=false).map((x){final id=x.id,incoming=tr.where((z)=>z['productId']?.toString()==id).fold<double>(0,(a,z)=>a+n(z['quantity'])),other=or.where((z)=>z['productId']?.toString()==id).fold<double>(0,(a,z)=>a+n(z['quantity'])),sold=sales.fold<double>(0,(a,z){final items=z['items'];if(items is! List)return a;return a+items.whereType<Map>().where((i)=>i['productId']?.toString()==id).fold<double>(0,(b,i)=>b+n(i['quantity']));});return Card(child:ListTile(title:Text(x.data()['name']?.toString()??id),subtitle:Text('Opening: 0  •  Received: ${incoming.toStringAsFixed(2)}  •  Other: ${other.toStringAsFixed(2)}  •  Sold: ${sold.toStringAsFixed(2)}'),trailing:Text('${(incoming+other-sold).toStringAsFixed(2)} Box',style:const TextStyle(fontWeight:FontWeight.bold))));})]);});});});});}
}
