import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'production_stock_page.dart';
import 'retail_stock_page.dart';

class StockManagementPage extends StatefulWidget { const StockManagementPage({super.key}); @override State<StockManagementPage> createState()=>_StockManagementPageState(); }
class _StockManagementPageState extends State<StockManagementPage>{bool loading=true,retailUser=false;String shopName='Retail Shop';
 @override void initState(){super.initState();_load();}
 Future<void> _load()async{final uid=FirebaseAuth.instance.currentUser?.uid;if(uid!=null){final d=(await FirebaseFirestore.instance.collection('users').doc(uid).get()).data()??{};retailUser=d['role']=='retail_shop_user';shopName=d['shopName']?.toString()??shopName;}if(mounted)setState(()=>loading=false);}
 Widget card(BuildContext context,{required IconData icon,required String title,required String subtitle,required VoidCallback onTap})=>Card(child:ListTile(minVerticalPadding:20,leading:CircleAvatar(child:Icon(icon)),title:Text(title,style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text(subtitle),trailing:const Icon(Icons.chevron_right),onTap:onTap));
 @override Widget build(BuildContext context){if(loading)return const Scaffold(body:Center(child:CircularProgressIndicator()));return Scaffold(appBar:AppBar(title:const Text('Stock Management')),body:ListView(padding:const EdgeInsets.all(16),children:[Text(retailUser?'$shopName Stock':'Select Stock Location',style:const TextStyle(fontSize:24,fontWeight:FontWeight.bold)),const SizedBox(height:8),Text(retailUser?'View only your assigned retail shop stock.':'Choose whether you want to view Production Unit stock or Retail Shop stock.'),const SizedBox(height:20),if(!retailUser)card(context,icon:Icons.factory_outlined,title:'Production Unit',subtitle:'Production minus quantities transferred to retail shops.',onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const ProductionStockPage()))),if(!retailUser)const SizedBox(height:12),card(context,icon:Icons.store_outlined,title:retailUser?shopName:'Retail Shop',subtitle:retailUser?'Only your assigned shop stock is available.':'Select a particular retail shop and view its item-wise stock.',onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const RetailStockPage()))) ]));}
}