import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import '../models/party.dart';
import '../models/transaction.dart';
import '../services/firestore_service.dart';

class TransactionsPage extends StatefulWidget { const TransactionsPage({super.key}); @override State<TransactionsPage> createState()=>_TransactionsPageState(); }
class _TransactionsPageState extends State<TransactionsPage>{
 DateTime selectedDate=DateTime.now(); String transactionType='Receipt',account='Cash'; Party? selectedParty; String? selectedPartyId,editingId,shopId; String shopName='Retail Shop'; bool retailUser=false,loading=true,saving=false;
 final amountController=TextEditingController(); final descriptionController=TextEditingController();
 static const types=['Receipt','Payment','Commission Payment','Capital','Others'];
 @override void initState(){super.initState();_profile();}
 @override void dispose(){amountController.dispose();descriptionController.dispose();super.dispose();}
 Future<void> _profile()async{final uid=FirebaseAuth.instance.currentUser?.uid;if(uid!=null){final d=(await FirebaseFirestore.instance.collection('users').doc(uid).get()).data()??{};if(mounted)setState((){retailUser=d['role']=='retail_shop_user';shopId=d['shopId']?.toString();shopName=d['shopName']?.toString()??'Retail Shop';loading=false;});}else if(mounted)setState(()=>loading=false);}
 String fd(DateTime d)=>'${d.day.toString().padLeft(2,'0')}-${d.month.toString().padLeft(2,'0')}-${d.year}';
 Future<void> pickDate()async{final p=await showDatePicker(context:context,initialDate:selectedDate,firstDate:DateTime(2020),lastDate:DateTime(2100));if(p!=null&&mounted)setState(()=>selectedDate=p);}
 void clear(){amountController.clear();descriptionController.clear();setState((){selectedDate=DateTime.now();transactionType='Receipt';account='Cash';selectedParty=null;selectedPartyId=null;editingId=null;});}
 Future<void> save()async{final amount=double.tryParse(amountController.text.trim())??0;if(amount<=0){msg('Enter an amount greater than zero.');return;}if(retailUser&&transactionType=='Payment'){selectedPartyId=null;selectedParty=null;}else if(transactionType!='Others'&&selectedParty==null){msg('Please select a party.');return;}final t=HisabTransaction(id:editingId??'',date:selectedDate,type:transactionType,amount:amount,account:account,partyId:selectedParty?.id??'',partyName:retailUser&&transactionType=='Payment'?'Production Unit':selectedParty?.name??'',description:descriptionController.text.trim(),shopId:shopId??'');setState(()=>saving=true);try{if(editingId==null){await FirestoreService.instance.add('transactions',t.toMap());msg('Transaction saved successfully.');}else{await FirestoreService.instance.update('transactions',editingId!,t.toMap());final admin=await FirestoreService.instance.isAdmin();msg(admin?'Transaction updated successfully.':'Edit request sent to Admin for approval.');}clear();}catch(e){if(mounted){setState(()=>saving=false);msg('Unable to save transaction: $e');}}}
 void msg(String s){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));}
 void edit(HisabTransaction t,List<Party> parties){Party? p;for(final x in parties){if(x.id==t.partyId){p=x;break;}}setState((){editingId=t.id;selectedDate=t.date;transactionType=t.type;account=t.account=='Bank'?'Bank':'Cash';selectedParty=p;selectedPartyId=t.partyId.isEmpty?null:t.partyId;amountController.text=t.amount.toStringAsFixed(2);descriptionController.text=t.description;});}
 Future<void> del(HisabTransaction t)async{final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Delete Transaction?'),content:Text('${t.type} ₹${t.amount.toStringAsFixed(2)}'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('CANCEL')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('DELETE'))]));if(ok!=true)return;try{await FirestoreService.instance.delete('transactions',t.id);final admin=await FirestoreService.instance.isAdmin();msg(admin?'Transaction deleted successfully.':'Delete request sent to Admin for approval.');}catch(e){msg('Unable to delete transaction: $e');}}
 Future<void> addParty()async{final n=TextEditingController(),ph=TextEditingController();final r=await showDialog<Party>(context:context,builder:(c)=>AlertDialog(title:const Text('Add New Party'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:const InputDecoration(labelText:'Party Name',border:OutlineInputBorder())),const SizedBox(height:10),TextField(controller:ph,decoration:const InputDecoration(labelText:'Phone',border:OutlineInputBorder()))]),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('CANCEL')),FilledButton(onPressed:()async{if(n.text.trim().isEmpty)return;final p=Party(id:'',name:n.text.trim(),phone:ph.text.trim());final id=await FirestoreService.instance.add('parties',p.toMap());if(c.mounted)Navigator.pop(c,Party(id:id,name:p.name,phone:p.phone));},child:const Text('SAVE'))]));n.dispose();ph.dispose();if(r!=null&&mounted)setState((){selectedParty=r;selectedPartyId=r.id;});}
 Widget form(List<Party> parties){final productionPayment=retailUser&&transactionType=='Payment';return Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(editingId==null?'Transaction Entry':'Edit Transaction',style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold))),if(editingId!=null)TextButton(onPressed:clear,child:const Text('CANCEL EDIT'))]),const SizedBox(height:14),InkWell(onTap:pickDate,child:InputDecorator(decoration:const InputDecoration(labelText:'Date',border:OutlineInputBorder()),child:Text(fd(selectedDate)))),const SizedBox(height:14),DropdownButtonFormField<String>(initialValue:transactionType,items:types.map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v){if(v!=null)setState((){transactionType=v;if(retailUser&&v=='Payment'){selectedParty=null;selectedPartyId=null;}});},decoration:const InputDecoration(labelText:'Transaction Type',border:OutlineInputBorder())),if(productionPayment)...[const SizedBox(height:14),const InputDecorator(decoration:InputDecoration(labelText:'Payment To',border:OutlineInputBorder()),child:Text('Production Unit'))]else if(transactionType!='Others')...[const SizedBox(height:14),DropdownButtonFormField<String>(initialValue:selectedPartyId,items:parties.map((p)=>DropdownMenuItem(value:p.id,child:Text(p.name))).toList(),onChanged:(v){if(v==null)return;setState((){selectedPartyId=v;selectedParty=parties.firstWhere((p)=>p.id==v);});},decoration:const InputDecoration(labelText:'Party',border:OutlineInputBorder())),Align(alignment:Alignment.centerRight,child:TextButton.icon(onPressed:addParty,icon:const Icon(Icons.person_add_alt_1),label:const Text('ADD NEW PARTY'))],const SizedBox(height:10),DropdownButtonFormField<String>(initialValue:account,items:const[DropdownMenuItem(value:'Cash',child:Text('Cash')),DropdownMenuItem(value:'Bank',child:Text('Bank'))],onChanged:(v){if(v!=null)setState(()=>account=v);},decoration:const InputDecoration(labelText:'Payment Account',border:OutlineInputBorder())),const SizedBox(height:14),TextField(controller:amountController,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Amount',prefixText:'₹ ',border:OutlineInputBorder())),const SizedBox(height:14),TextField(controller:descriptionController,maxLines:2,decoration:const InputDecoration(labelText:'Description / Remark',border:OutlineInputBorder())),if(retailUser&&shopId!=null)...[const SizedBox(height:10),Text('Shop: $shopName',style:const TextStyle(fontWeight:FontWeight.w600))],const SizedBox(height:16),SizedBox(width:double.infinity,height:48,child:FilledButton.icon(onPressed:saving?null:save,icon:saving?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.save),label:Text(saving?'SAVING...':'SAVE'))])));}
 Widget history(List<Party> parties)=>StreamBuilder<List<Map<String,dynamic>>>(stream:FirestoreService.instance.stream('transactions'),builder:(context,s){if(s.hasError)return Text('Error loading transaction history: ${s.error}');if(!s.hasData)return const Center(child:CircularProgressIndicator());final list=s.data!.map((x)=>HisabTransaction.fromMap(x['id'].toString(),x)).toList()..sort((a,b)=>b.date.compareTo(a.date));if(list.isEmpty)return const Card(child:Padding(padding:EdgeInsets.all(20),child:Text('No transactions found.')));return Card(child:Column(children:[const Padding(padding:EdgeInsets.all(16),child:Align(alignment:Alignment.centerLeft,child:Text('Transaction History',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)))),...list.map((t)=>ListTile(title:Text(t.partyName.isEmpty?t.type:'${t.type} • ${t.partyName}'),subtitle:Text('${fd(t.date)} • ${t.account}${t.description.isEmpty?'':' • ${t.description}'}'),trailing:SizedBox(width:105,child:Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.end,children:[Text('₹${t.amount.toStringAsFixed(2)}',style:const TextStyle(fontWeight:FontWeight.bold)),Row(mainAxisAlignment:MainAxisAlignment.end,children:[IconButton(icon:const Icon(Icons.edit_outlined,size:19),onPressed:()=>edit(t,parties)),IconButton(icon:const Icon(Icons.delete_outline,size:19),onPressed:()=>del(t))])])))]));});
 @override Widget build(BuildContext context){if(loading)return const Scaffold(body:Center(child:CircularProgressIndicator()));return Scaffold(appBar:AppBar(title:Text(retailUser?'Retail Transactions':'Transactions')),body:StreamBuilder<List<Map<String,dynamic>>>(stream:FirestoreService.instance.stream('parties'),builder:(context,s){if(s.hasError)return Center(child:Text('Error loading parties: ${s.error}'));if(!s.hasData)return const Center(child:CircularProgressIndicator());final parties=s.data!.map((x)=>Party.fromMap(x['id'].toString(),x)).where((p)=>p.active).toList();return ListView(padding:const EdgeInsets.all(16),children:[if(retailUser)Card(child:ListTile(leading:const Icon(Icons.store),title:Text(shopName),subtitle:const Text('Retail shop transactions')),),form(parties),const SizedBox(height:18),history(parties)]);});}
}
