import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import '../models/party.dart';
import '../models/transaction.dart';
import '../services/firestore_service.dart';
class TransactionsPage extends StatefulWidget{const TransactionsPage({super.key});@override State<TransactionsPage> createState()=>_TransactionsPageState();}
class _TransactionsPageState extends State<TransactionsPage>{DateTime date=DateTime.now();String type='Receipt',account='Cash';Party? party;String? partyId,editId,shopId,shopName;bool retail=false,loading=true,saving=false;final amount=TextEditingController(),remark=TextEditingController();const types=['Receipt','Payment','Commission Payment','Capital','Others'];
 @override void initState(){super.initState();profile();} @override void dispose(){amount.dispose();remark.dispose();super.dispose();}
 Future<void> profile()async{final u=FirebaseAuth.instance.currentUser;if(u!=null){final d=(await FirebaseFirestore.instance.collection('users').doc(u.uid).get()).data()??{};if(mounted)setState((){retail=d['role']=='retail_shop_user';shopId=d['shopId']?.toString();shopName=d['shopName']?.toString()??'Retail Shop';loading=false;});}else if(mounted)setState(()=>loading=false);}
 String fd(DateTime d)=>'${d.day.toString().padLeft(2,'0')}-${d.month.toString().padLeft(2,'0')}-${d.year}';
 Future<void> pick()async{final x=await showDatePicker(context:context,initialDate:date,firstDate:DateTime(2020),lastDate:DateTime(2100));if(x!=null&&mounted)setState(()=>date=x);}
 void clear(){amount.clear();remark.clear();setState((){date=DateTime.now();type='Receipt';account='Cash';party=null;partyId=null;editId=null;saving=false;});}
 Future<void> save()async{final a=double.tryParse(amount.text.trim())??0;if(a<=0){msg('Enter an amount greater than zero.');return;}if(type!='Others'&&!(retail&&type=='Payment')&&party==null){msg('Please select a party.');return;}setState(()=>saving=true);final t=HisabTransaction(id:editId??'',date:date,type:type,amount:a,account:account,partyId:party?.id??'',partyName:retail&&type=='Payment'?'Production Unit':party?.name??'',description:remark.text.trim(),shopId:shopId??'');try{if(editId==null){await FirestoreService.instance.add('transactions',t.toMap());msg('Transaction saved successfully.');}else{await FirestoreService.instance.update('transactions',editId!,t.toMap());final admin=await FirestoreService.instance.isAdmin();msg(admin?'Transaction updated successfully.':'Edit request sent to Admin for approval.');}clear();}catch(e){if(mounted){setState(()=>saving=false);msg('Unable to save transaction: $e');}}}
 void msg(String s){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));}
 void edit(HisabTransaction t,List<Party> ps){party=ps.where((p)=>p.id==t.partyId).firstOrNull;setState((){editId=t.id;date=t.date;type=t.type;account=t.account=='Bank'?'Bank':'Cash';partyId=t.partyId.isEmpty?null:t.partyId;amount.text=t.amount.toStringAsFixed(2);remark.text=t.description;});}
 Future<void> del(HisabTransaction t)async{final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Delete Transaction?'),content:Text('${t.type} ₹${t.amount.toStringAsFixed(2)}'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('CANCEL')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('DELETE'))]));if(ok!=true)return;try{await FirestoreService.instance.delete('transactions',t.id);final admin=await FirestoreService.instance.isAdmin();msg(admin?'Transaction deleted successfully.':'Delete request sent to Admin for approval.');}catch(e){msg('Unable to delete transaction: $e');}}
 Future<void> addParty()async{final n=TextEditingController();final r=await showDialog<Party>(context:context,builder:(c)=>AlertDialog(title:const Text('Add Party'),content:TextField(controller:n,decoration:const InputDecoration(labelText:'Party Name')),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('CANCEL')),FilledButton(onPressed:()async{if(n.text.trim().isEmpty)return;final p=Party(id:'',name:n.text.trim(),phone:'');final id=await FirestoreService.instance.add('parties',p.toMap());if(c.mounted)Navigator.pop(c,Party(id:id,name:p.name,phone:''));},child:const Text('SAVE'))]));n.dispose();if(r!=null&&mounted)setState((){party=r;partyId=r.id;});}
 Widget form(List<Party> ps){final pp=retail&&type=='Payment';return Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(children:[Row(children:[Expanded(child:Text(editId==null?'Transaction Entry':'Edit Transaction',style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold))),if(editId!=null)TextButton(onPressed:clear,child:const Text('CANCEL'))]),const SizedBox(height:12),InkWell(onTap:pick,child:InputDecorator(decoration:const InputDecoration(labelText:'Date',border:OutlineInputBorder()),child:Text(fd(date)))),const SizedBox(height:12),DropdownButtonFormField<String>(initialValue:type,items:types.map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setState(()=>type=v??type),decoration:const InputDecoration(labelText:'Transaction Type',border:OutlineInputBorder())),if(pp)...[const SizedBox(height:12),const InputDecorator(decoration:InputDecoration(labelText:'Payment To',border:OutlineInputBorder()),child:Text('Production Unit'))]else if(type!='Others')...[const SizedBox(height:12),DropdownButtonFormField<String>(initialValue:partyId,items:ps.map((p)=>DropdownMenuItem(value:p.id,child:Text(p.name))).toList(),onChanged:(v){final p=ps.where((x)=>x.id==v).firstOrNull;setState((){partyId=v;party=p;});},decoration:const InputDecoration(labelText:'Party',border:OutlineInputBorder())),Align(alignment:Alignment.centerRight,child:TextButton.icon(onPressed:addParty,icon:const Icon(Icons.person_add),label:const Text('ADD PARTY'))],const SizedBox(height:12),DropdownButtonFormField<String>(initialValue:account,items:const[DropdownMenuItem(value:'Cash',child:Text('Cash')),DropdownMenuItem(value:'Bank',child:Text('Bank'))],onChanged:(v)=>setState(()=>account=v??account),decoration:const InputDecoration(labelText:'Account',border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:amount,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Amount',prefixText:'₹ ',border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:remark,maxLines:2,decoration:const InputDecoration(labelText:'Description / Remark',border:OutlineInputBorder())),if(retail)Align(alignment:Alignment.centerLeft,child:Text('Shop: $shopName')),const SizedBox(height:14),SizedBox(width:double.infinity,height:48,child:FilledButton(onPressed:saving?null:save,child:Text(saving?'SAVING...':'SAVE')))]));}
 Widget history(List<Party> ps)=>StreamBuilder<List<Map<String,dynamic>>>(stream:FirestoreService.instance.stream('transactions'),builder:(c,s){if(s.hasError)return Text('Error loading transactions: ${s.error}');if(!s.hasData)return const CircularProgressIndicator();final list=s.data!.map((x)=>HisabTransaction.fromMap(x['id'].toString(),x)).where((x)=>!retail||x.shopId==shopId).toList()..sort((a,b)=>b.date.compareTo(a.date));return Card(child:Column(children:[const Padding(padding:EdgeInsets.all(16),child:Align(alignment:Alignment.centerLeft,child:Text('Transaction History',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)))),...list.map((t)=>ListTile(title:Text(t.partyName.isEmpty?t.type:'${t.type} • ${t.partyName}'),subtitle:Text('${fd(t.date)} • ${t.account}'),trailing:Wrap(children:[Text('₹${t.amount.toStringAsFixed(2)}'),IconButton(onPressed:()=>edit(t,ps),icon:const Icon(Icons.edit_outlined)),IconButton(onPressed:()=>del(t),icon:const Icon(Icons.delete_outline))]))]));});
 @override Widget build(BuildContext context){if(loading)return const Scaffold(body:Center(child:CircularProgressIndicator()));return Scaffold(appBar:AppBar(title:Text(retail?'Retail Transactions':'Transactions')),body:StreamBuilder<List<Map<String,dynamic>>>(stream:FirestoreService.instance.stream('parties'),builder:(c,s){if(s.hasError)return Center(child:Text('Error loading parties: ${s.error}'));if(!s.hasData)return const Center(child:CircularProgressIndicator());final ps=s.data!.map((x)=>Party.fromMap(x['id'].toString(),x)).where((p)=>p.active).toList();return ListView(padding:const EdgeInsets.all(16),children:[if(retail)Card(child:ListTile(title:Text(shopName),subtitle:const Text('Assigned retail shop'))),form(ps),const SizedBox(height:16),history(ps)]);});}
}
